version: "3.0"

services:

  mysql:
    image: mysql:8
    restart: always
    env_file: ./api/environments/dev.env
    ports:
      - "3306:3306"
    expose:
      - "3306"

  redis:
    image: redis:5
    restart: always
    env_file: ./api/environments/dev.env
    ports:
      - "6379:6379"
    expose:
      - "6379"
